---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    app: pvc1
  namespace: default
spec:
  storageClassName: storageclass1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
