---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
  labels:
    app: pvc2
  namespace: default
spec:
  storageClassName: storageclass2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
