---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass2
  labels:
    app: storageclass2
  namespace: default
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.121.135
  share: /i_am_node/nfs1
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
